<a href="https://colab.research.google.com/github/AlexaMravko/EMV/blob/main/17FebPCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ANÁLISIS DE SENSIBILIDAD 

In [1]:
import numpy as np

import pandas as pd 


## Reanalizar la DataBase de Iris de Fisher

In [2]:
url= "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

names= ["spal-lenght", "speal-width", "petal-lenght", "petal-width", "Class"]

datairis = pd.read_csv(url,names=names)

datairis.head(10)

# el nombre de las columnas lo otorgamos nosotros 
# elementos categoricos 


spal-lenght  speal-width  petal-lenght  petal-width        Class
0          5.1          3.5           1.4          0.2  Iris-setosa
1          4.9          3.0           1.4          0.2  Iris-setosa
2          4.7          3.2           1.3          0.2  Iris-setosa
3          4.6          3.1           1.5          0.2  Iris-setosa
4          5.0          3.6           1.4          0.2  Iris-setosa
5          5.4          3.9           1.7          0.4  Iris-setosa
6          4.6          3.4           1.4          0.3  Iris-setosa
7          5.0          3.4           1.5          0.2  Iris-setosa
8          4.4          2.9           1.4          0.2  Iris-setosa
9          4.9          3.1           1.5          0.1  Iris-setosa

## Preprocesamiento de datos

In [3]:
A= datairis.drop("Class",1) #Cleaning 

print(A)

     spal-lenght  speal-width  petal-lenght  petal-width
0            5.1          3.5           1.4          0.2
1            4.9          3.0           1.4          0.2
2            4.7          3.2           1.3          0.2
3            4.6          3.1           1.5          0.2
4            5.0          3.6           1.4          0.2
..           ...          ...           ...          ...
145          6.7          3.0           5.2          2.3
146          6.3          2.5           5.0          1.9
147          6.5          3.0           5.2          2.0
148          6.2          3.4           5.4          2.3
149          5.9          3.0           5.1          1.8

[150 rows x 4 columns]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  """Entry point for launching an IPython kernel.


In [4]:
B= datairis["Class"] #accesar a columnas y tener los datos originales 
B

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Class, Length: 150, dtype: object

In [5]:
!pip install scikit-learn

## Toy Example 

In [6]:
data= np.reshape(np.random.rand(20),(10,2))
print(data)

[[0.33476243 0.40427708]
 [0.71318471 0.73004515]
 [0.92583481 0.06447977]
 [0.70528605 0.1405688 ]
 [0.50956477 0.27972987]
 [0.9815137  0.66432102]
 [0.72285298 0.69247493]
 [0.54520305 0.39484494]
 [0.37551431 0.08257546]
 [0.44910423 0.15665628]]


In [7]:
labels= np.random.randint(2, size=10)
labels

array([1, 0, 1, 1, 0, 0, 1, 0, 1, 1])

In [8]:
from sklearn.model_selection import train_test_split
data= np.reshape(np.random.random(20),(10,2)) #10 training examples 
labels= np.random.randint(2, size=10) #10 labels 

In [9]:
X= pd.DataFrame(data, columns=['Column_1', 'Column_2'])
y= pd.Series(labels)

print(X)
print(y)

   Column_1  Column_2
0  0.347683  0.719823
1  0.699212  0.394800
2  0.235766  0.866161
3  0.825230  0.610423
4  0.518041  0.979780
5  0.220028  0.980680
6  0.187225  0.715662
7  0.947517  0.116652
8  0.507265  0.453649
9  0.951554  0.372205
0    0
1    0
2    1
3    1
4    1
5    0
6    1
7    1
8    1
9    1
dtype: int64


In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [11]:
X_test

Column_1  Column_2
2  0.235766  0.866161
8  0.507265  0.453649

In [12]:
y_test

2    1
8    1
dtype: int64

In [13]:
X_train

Column_1  Column_2
4  0.518041  0.979780
9  0.951554  0.372205
1  0.699212  0.394800
6  0.187225  0.715662
7  0.947517  0.116652
3  0.825230  0.610423
0  0.347683  0.719823
5  0.220028  0.980680

In [14]:
y_train

4    1
9    1
1    0
6    1
7    1
3    1
0    0
5    0
dtype: int64

In [16]:
from numpy.ma.core import reshape
from scipy.stats import multivariate_normal

x,y = np.mgrid[-1.0:1.0:30j,-1.0:1.0:30j]
#need an (N,2) array of (x,y) pairs. 

xy= np.column_stack([x.flat,y.flat])

mu= np.array([0.0,0.0])

sigma= np.array([.025,3])
covariance= np.diag(sigma**2)

z= multivariate_normal.pdf(xy, mean=mu, cov=covariance)

#reshape back to a (30, 30) grid 

z= z.reshape(x.shape)
z

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [1.36995935e-301, 1.38013272e-301, 1.38964705e-301,
        1.39848772e-301, 1.40664106e-301, 1.41409443e-301,
        1.42083623e-301, 1.42685592e-301, 1.43214406e-301,
        1.43669235e-301, 1.44049362e-301, 1.44354188e-301,
        1.44583231e-301, 1.44736128e-301, 1.44812637e-301,
        1.44812637e-301, 1.44736128e-301, 1.44583231e-301,
        1.44354188e-301, 1.44049362e-301, 1.43669235e-3